name: Update Matches Data

on:
  schedule:
    # يشتغل كل 3 ساعات
    - cron: '0 */3 * * *'
  workflow_dispatch: # زر للتشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch_matches.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add matches.json
          git commit -m "Update matches data" || exit 0
          git push
